---
version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: cron
      cronjob: "4 4 * * *"
      timezone: America/Chicago
    allow:
      - dependency-type: all
