inherit_gem:
  runger_style:
    - rulesets/default.yml # gem 'rubocop'
    - rulesets/performance.yml # gem 'rubocop-performance'
    - rulesets/rake.yml # gem 'rubocop-rake'
    - rulesets/rspec.yml # gem 'rubocop-rspec'
