Layout/DotPosition:
  EnforcedStyle: trailing
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/LineLength:
  Max: 100
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/EmptyCaseCondition:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
