---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
notifications:
  email:
    on_success: never
    on_failure: never
script:
  - bin/rubocop $(git ls-tree -r HEAD --name-only) --force-exclusion --format clang
  - bin/rspec
