#!/usr/bin/env ruby

# frozen_string_literal: true

require 'slop'
require_relative '../lib/fcom.rb'

opts =
  Slop.parse do |o|
    o.banner = <<~BANNER

      Usage: fcom <search string> [options]

      Examples:
        fcom update
        fcom 'def update'
        fcom "def update" --days 60
        fcom "[Uu]ser.*slug" -d 365 --regex
        fcom options --path spec/
        fcom "line.(green|red)" -d 365 --regex --repo davidrunger/fcom
    BANNER

    Fcom.define_slop_options(o)

    o.on('-v', '--version', 'print the version') do
      puts(Fcom::VERSION)
      exit
    end
    o.on('-h', '--help', 'print this help information') do
      puts(o)
      exit
    end
  end

# Note: mutating the globally accessible `Fcom.logger` constant like this is not thread-safe
Fcom.logger.level = opts.debug? ? Logger::DEBUG : Logger::WARN

if opts.parse_mode?
  Fcom.warn_if_config_file_repo_option_missing
  Fcom::Parser.new(opts).parse
else
  Fcom::Querier.new(opts).query
end
